source 'https://github.com/CocoaPods/Specs.git'

target 'BBForm', :exclusive => true do
  pod "BBForm", :path => "../"
  pod 'TPKeyboardAvoiding'
end

target 'Tests', :exclusive => true do
  pod "BBForm", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
