target 'BBForm', :exclusive => true do
  pod "BBForm", :path => "../"
  pod 'Reveal-iOS-SDK'
end

target 'Tests', :exclusive => true do
  pod "BBForm", :path => "../"

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
end
